cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'autojump'
brew 'bash-completion'
brew 'coreutils'
brew 'dfu-programmer'
brew 'git'
brew 'hub'
brew 'jp2a'
brew 'jq'
brew 'kotlin'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'rbenv'
brew 'readline'
brew 'roundup'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'

# cask 'anki'
# cask 'bartender'
# cask 'bettertouchtool'
# cask 'double-commander'
# cask 'dropbox'
# cask 'firefox'
# cask 'google-chrome'
# cask 'hammerspoon'
# cask 'hyperswitch'
# cask 'intellij-idea'
# cask 'istat-menus'
# cask 'iterm2'
# cask 'itunes'
# cask 'limechat'
# cask 'omnifocus'
# cask 'postbox'
# cask 'screenhero'
# cask 'slack'
# cask 'sourcetree'
# cask 'spotify'
# cask 'steam'
# cask 'sublime-text'
# cask 'tunnelbear'
# cask 'vyprvpn'
# cask 'webstorm'
