cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

cask 'xquartz' # required for libcaca
cask 'java'    # required for gradle

brew 'bash-completion'
brew 'bat'
brew 'coreutils'
brew 'dfu-programmer'
brew 'exa'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'gradle'
brew 'httpie'
brew 'hub'
brew 'jp2a'
brew 'jenv'
brew 'jq'
brew 'kotlin'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'maven'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'rbenv'
brew 'readline'
brew 'roundup'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'spark'
brew 'tmux'
brew 'tokei'
brew 'unrar'
brew 'weechat'
brew 'wget'
brew 'yarn'
brew 'zsh'

# cask 'anki'
cask 'bartender'
cask 'bettertouchtool'
# cask 'double-commander'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'hammerspoon'
cask 'hyperswitch'
cask 'jetbrains-toolbox'
# cask 'intellij-idea'
cask 'istat-menus'
cask 'iterm2'
# cask 'itunes'
# cask 'limechat'
# cask 'omnifocus'
cask 'postbox'
# cask 'screenhero'
cask 'slack'
# cask 'sourcetree'
cask 'spotify'
# cask 'steam'
# cask 'sublime-text'
# cask 'tunnelbear'
# cask 'vyprvpn'
# cask 'webstorm'
